version: "3.9"

services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  web:
    container_name: web_app
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn payment_service.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
    env_file:
      - .env.prod
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web

volumes:
  pg_data:
  static_volume:
